=== NordicSemiconductor/nrfprogrammer-firmware-images/application.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "title": "nRF Programmer firmware images application manifest",
  "description": "Describes the manifest that decribes application firmware.",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "URL to the JSON schema in use",
      "type": "string",
      "format": "url"
    },
    "app_id": {
      "description": "Globally unique application ID",
      "examples": ["0e68201e-845d-424b-b3c9-1665b4788ef1"],
      "type": "string",
      "format": "uuid",
      "minLength": 1
    },
    "app_name": {
      "description": "Display name of the application",
      "examples": ["Peripheral LBS"],
      "type": "string",
      "minLength": 1
    },
    "user_id": {
      "description": "ID of the application author. '00005900-0000-1000-8000-00805F9B34FB' is Nordic Semiconductor.",
      "examples": [
        "00005900-0000-1000-8000-00805F9B34FB",
        "9ff7fed0-ca14-42c2-94f0-c52ec849c51e"
      ],
      "type": "string",
      "format": "uuid",
      "minLength": 1
    },
    "description": {
      "description": "Application description",
      "examples": [
        "The Peripheral LBS sample demonstrates how to use the LED Button Service (LBS)."
      ],
      "type": "string",
      "minLength": 1
    },
    "tags": {
      "description": "Listf of tags (only lowercase characters and space)",

      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "pattern": "^[a-z ]{1,}$",
        "examples": ["lbs", "led", "button"]
      }
    },
    "versions": {
      "description": "Available versions",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "version": {
            "description": "The semantic version identifier",
            "examples": ["1.0.0"],
            "type": "string",
            "pattern": "^[0-9]+.[0-9]+.[0-9]+$"
          },
          "release_notes": {
            "description": "Release notes for this version",
            "examples": ["Initial release"],
            "type": "string",
            "minLength": 1
          },
          "requires_bonding": {
            "description": "Whether this version of the application requires Bluetooth Low Energy bonding.",
            "type": "boolean"
          },
          "links": {
            "description": "Links to further information about this version of the application",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "description": "Label for the link",
                  "examples": ["Documentation"],
                  "type": "string",
                  "minLength": 1
                },
                "url": {
                  "description": "The URL to use for the link",
                  "examples": [
                    "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.7.0/nrf/samples/bluetooth/peripheral_lbs/README.html"
                  ],
                  "type": "string",
                  "format": "url"
                }
              },
              "additionalProperties": false,
              "required": ["text", "url"]
            }
          },
          "board": {
            "description": "Describes the hardware this application can be flashed to",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "description": "The identifier of the board",
                  "enum": ["thingy53_nrf5340"]
                },
                "build_config": {
                  "description": "The available images for the board",
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "description": "The identifier of the image",
                        "examples": ["sample"],
                        "type": "string",
                        "minLength": 1
                      },
                      "file": {
                        "description": "The filename of the image, relative to the URL of the manifest",
                        "type": "string",
                        "minLength": 1
                      }
                    },
                    "required": ["name", "file"],
                    "additionalProperties": false
                  }
                }
              },
              "required": ["name", "build_config"],
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "version",
          "release_notes",
          "requires_bonding",
          "links",
          "board"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "app_id",
    "app_name",
    "user_id",
    "description",
    "tags",
    "versions"
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Mesh sensor server/mesh_sensor_server.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "3fb038be-b292-4452-a1cf-2e72298c6d1e",
  "app_name": "Bluetooth mesh: sensor server",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The BluetoothÂ® mesh sensor sample demonstrates how to set up a basic mesh Sensor Server model application that provides sensor data to one Sensor Client model. Four different sensor types are used to showcase different ways for the server to publish data. In addition, the sample demonstrates usage of both single-channel sensor types and sensor series types.",
  "tags": ["mesh", "sensor", "temperature", "presence"],
  "versions": [
    {
      "version": "1.0.0",
      "release_notes": "Initial release based on NCS release 1.9.1",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/nrf/samples/bluetooth/mesh/sensor_server/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_sensor_server_1.0.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.3.0",
      "release_notes": "- Enabled the CONFIG_SOC_FLASH_NRF_PARTIAL_ERASE Kconfig option,\n- Max size of Proxy Filter list increased from 3 to 16.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.3.0/nrf/samples/bluetooth/mesh/sensor_server/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_sensor_server_2.3.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.5.0",
      "release_notes": "- Support for motion threshold as a setting for the presence detection,\n- Support for ambient light level sensor,\n- Link layer payload size over GATT increased from 27 to maximum 37 to avoid fragmentation of outgoing messages to the proxy client,\n- Support for Composition Data Pages 1 and 2 (Bluetooth mesh 1.1),\n- Fixed value of Time Since Presence Detected when delta would exceed the range.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/samples/bluetooth/mesh/sensor_server/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_sensor_server_2.5.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Status/peripheral_status.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "1a9e4d1c-d946-46ab-b97a-accc99d99309",
  "app_name": "Peripheral Status",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The peripheral status sample demonstrates how to use the Nordic Status Message Service (NSMS) library.",
  "tags": ["status", "nsms", "notifications"],
  "versions": [
    {
      "version": "2.5.0",
      "release_notes": "Initial release from NCS 2.5.0.",
      "requires_bonding": true,
      "links": [
        {
          "text": "nRF Connect for Mobile (Android)",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp"
        },
        {
          "text": "nRF Connect for Mobile (iOS)",
          "url": "https://apps.apple.com/pl/app/nrf-connect-for-mobile/id1054362403"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/samples/bluetooth/peripheral_status/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "peripheral_status_2.5.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}
