=== NordicSemiconductor/nrfprogrammer-firmware-images/application.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "title": "nRF Programmer firmware images application manifest",
  "description": "Describes the manifest that decribes application firmware.",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "URL to the JSON schema in use",
      "type": "string",
      "format": "url"
    },
    "app_id": {
      "description": "Globally unique application ID",
      "examples": ["0e68201e-845d-424b-b3c9-1665b4788ef1"],
      "type": "string",
      "format": "uuid",
      "minLength": 1
    },
    "app_name": {
      "description": "Display name of the application",
      "examples": ["Peripheral LBS"],
      "type": "string",
      "minLength": 1
    },
    "user_id": {
      "description": "ID of the application author. '00005900-0000-1000-8000-00805F9B34FB' is Nordic Semiconductor.",
      "examples": [
        "00005900-0000-1000-8000-00805F9B34FB",
        "9ff7fed0-ca14-42c2-94f0-c52ec849c51e"
      ],
      "type": "string",
      "format": "uuid",
      "minLength": 1
    },
    "description": {
      "description": "Application description",
      "examples": [
        "The Peripheral LBS sample demonstrates how to use the LED Button Service (LBS)."
      ],
      "type": "string",
      "minLength": 1
    },
    "tags": {
      "description": "Listf of tags (only lowercase characters and space)",

      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "pattern": "^[a-z ]{1,}$",
        "examples": ["lbs", "led", "button"]
      }
    },
    "versions": {
      "description": "Available versions",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "version": {
            "description": "The semantic version identifier",
            "examples": ["1.0.0"],
            "type": "string",
            "pattern": "^[0-9]+.[0-9]+.[0-9]+$"
          },
          "release_notes": {
            "description": "Release notes for this version",
            "examples": ["Initial release"],
            "type": "string",
            "minLength": 1
          },
          "requires_bonding": {
            "description": "Whether this version of the application requires Bluetooth Low Energy bonding.",
            "type": "boolean"
          },
          "links": {
            "description": "Links to further information about this version of the application",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "description": "Label for the link",
                  "examples": ["Documentation"],
                  "type": "string",
                  "minLength": 1
                },
                "url": {
                  "description": "The URL to use for the link",
                  "examples": [
                    "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.7.0/nrf/samples/bluetooth/peripheral_lbs/README.html"
                  ],
                  "type": "string",
                  "format": "url"
                }
              },
              "additionalProperties": false,
              "required": ["text", "url"]
            }
          },
          "board": {
            "description": "Describes the hardware this application can be flashed to",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "description": "The identifier of the board",
                  "enum": ["thingy53_nrf5340"]
                },
                "build_config": {
                  "description": "The available images for the board",
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "description": "The identifier of the image",
                        "examples": ["sample"],
                        "type": "string",
                        "minLength": 1
                      },
                      "file": {
                        "description": "The filename of the image, relative to the URL of the manifest",
                        "type": "string",
                        "minLength": 1
                      }
                    },
                    "required": ["name", "file"],
                    "additionalProperties": false
                  }
                }
              },
              "required": ["name", "build_config"],
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "version",
          "release_notes",
          "requires_bonding",
          "links",
          "board"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "app_id",
    "app_name",
    "user_id",
    "description",
    "tags",
    "versions"
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Machine learning/machine_learning.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "f42ff902-45ca-4558-b8bc-4d9b798ee433",
  "app_name": "nRF Machine Learning",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The nRF Machine Learning application is an out of the box reference design of an embedded machine learning using Edge Impulse. The application gathers data from sensors, forwards data to the Edge Impulse platform, and runs the machine learning model. It also displays results of the machine learning model on LEDs. The Edge Impulse platform collects data from sensors, trains machine learning model, and deploys the model to your Nordic Semiconductorâ€™s device.",
  "tags": ["machine learning", "edge impulse"],
  "versions": [
    {
      "version": "1.0.0",
      "release_notes": "Initial release",
      "requires_bonding": true,
      "links": [
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/nrf/applications/machine_learning/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "machine_learning_1.0.0_thingy53_nrf5340_zrelease.zip"
            },
            {
              "name": "debug",
              "file": "machine_learning_1.0.0_thingy53_nrf5340_zdebug.zip"
            },
            {
              "name": "debug_rtt",
              "file": "machine_learning_1.0.0_thingy53_nrf5340_zdebug_rtt.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Matter weather station - Wi-Fi/matter_weather_station.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "715c3879-68ea-4d66-bdb7-2b87479aec26",
  "app_name": "Matter weather station - Wi-Fi",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "This Matter weather station application demonstrates the usage of the Matter application layer to build a weather station device. Such a device lets you remotely gather different kinds of data using the device sensors, such as temperature, air pressure, and relative humidity. The device works as a Matter accessory device, meaning it can be paired and controlled remotely over a Matter network built on top of Wi-Fi network.\n\nThis application requires nRF7002 Expansion Board.",
  "tags": ["matter", "chip", "weather station", "wifi"],
  "versions": [
    {
      "version": "2.5.0",
      "release_notes": "Initial release from NCS 2.5.0.",
      "requires_bonding": false,
      "links": [
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/applications/matter_weather_station/README.html"
        },
        {
          "text": "Matter (Project CHIP)",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/protocols/matter/index.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "matter_weather_station_nrf7002eb_2.5.0_thingy53.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Mesh light ctrl/mesh_light_ctrl.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "57133692-965b-4e53-b480-4dfbc27b6dbc",
  "app_name": "Bluetooth mesh: light fixture",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The BluetoothÂ® mesh light fixture sample demonstrates how to set up a light control mesh server model application, and control a dimmable LED with Bluetooth mesh using the Generic OnOff models.",
  "tags": ["mesh", "light fixture", "ctrl", "smart home"],
  "versions": [
    {
      "version": "1.0.0",
      "release_notes": "Initial release, based on NCS 1.9.1.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/nrf/samples/bluetooth/mesh/light_ctrl/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_light_ctrl_1.0.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.3.0",
      "release_notes": "- Enabled the CONFIG_SOC_FLASH_NRF_PARTIAL_ERASE Kconfig option.\n- The specification-defined illuminance regulator now selects the CONFIG_FPU option by default.\n- Added a configuration with support for storing data with Emergency data storage.\n- Changed the sample to restore Light state after power-down.\n- Max size of Proxy Filter list increased from 3 to 16.\n\nKnown issues:\n- Setting a publication may cause Thingy:53 to reboot.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.3.0/nrf/samples/bluetooth/mesh/light_ctrl/README.html"
        },
        {
          "text": "Emergency data storage (EMDS)",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.3.0/nrf/libraries/others/emds.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release (settings)",
              "file": "mesh_light_ctrl_2.3.0_thingy53_nrf5340.zip"
            },
            {
              "name": "release (emds)",
              "file": "mesh_light_ctrl_2.3.0_thingy53_nrf5340_emds.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.5.0",
      "release_notes": "- Publications fixed,\n- Link layer payload size over GATT increased from 27 to maximum 37 to avoid fragmentation of outgoing messages to the proxy client,\n- Support for Composition Data Pages 1 and 2 (Bluetooth mesh 1.1),\n- Added support for the Scene Server and Sensor Server models.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/samples/bluetooth/mesh/light_ctrl/README.html"
        },
        {
          "text": "Emergency data storage (EMDS)",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/libraries/others/emds.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release (settings)",
              "file": "mesh_light_ctrl_2.5.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Edge Impulse - Wi-Fi/edge_impulse.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "7f296ed9-a9fc-424d-b2ca-e2c17fa3eab6",
  "app_name": "Edge Impulse - Wi-Fi",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "Embedded machine learning application using Edge Impulse with nRF7002 Expansion Board support. The application gathers data from sensors over Wi-Fi and forwards to the Edge Impulse platform. The Edge Impulse platform collects data from sensors, trains machine learning model, and deploys the model to the Thingy:53 using nRF Edge Impulse mobile app.",
  "tags": ["machine learning", "edge impulse"],
  "versions": [
    {
      "version": "2.4.0",
      "release_notes": "Initial release",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Edge Impulse for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfei"
        },
        {
          "text": "nRF Edge Impulse for iOS",
          "url": "https://apps.apple.com/us/app/nrf-edge-impulse/id1557234087"
        },
        {
          "text": "Edge Impulse",
          "url": "https://edgeimpulse.com"
        },
        {
          "text": "Edge Impulse Studio",
          "url": "https://studio.edgeimpulse.com"
        },
        {
          "text": "Edge Impulse Documentation",
          "url": "https://docs.edgeimpulse.com"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "edge_impulse_wifi_2.4.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Mesh light switch/mesh_light_switch.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "54d9d2a9-fc5c-4311-8acc-8b3f21ece318",
  "app_name": "Bluetooth mesh: light switch",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The Bluetooth® mesh light switch sample can be used to change the state of light sources on other devices within the same mesh network. It also demonstrates how to use Bluetooth® mesh models by using the Generic OnOff Client model in an application.",
  "tags": ["mesh", "light switch", "button", "smart home"],
  "versions": [
    {
      "version": "1.0.0",
      "release_notes": "Initial release",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/nrf/samples/bluetooth/mesh/light_switch/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_light_switch_1.0.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.3.0",
      "release_notes": "- Enabled the CONFIG_SOC_FLASH_NRF_PARTIAL_ERASE Kconfig option.\n- Added support for running the light switch as a Low Power node.\n- Updated all samples to use the Partition Manager, replacing the use of the Device Tree Source flash partitions.\n- Max size of Proxy Filter list increased from 3 to 16.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.3.0/nrf/samples/bluetooth/mesh/light_switch/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_light_switch_2.3.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.5.0",
      "release_notes": "- Link layer payload size over GATT increased from 27 to maximum 37 to avoid fragmentation of outgoing messages to the proxy client.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/samples/bluetooth/mesh/light_switch/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_light_switch_2.5.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Mesh dimmer/mesh_light_dimmer.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "abd74ae0-0f96-49db-904d-500ef3d02bf7",
  "app_name": "Bluetooth mesh: light dimmer and scene selector",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The BluetoothÂ® mesh light dimmer and scene selector sample demonstrates how to set up a light dimmer and scene selector application, and control dimmable LEDs with Bluetooth mesh using the Generic Level models, the Generic OnOff models, and the Scene models.",
  "tags": ["mesh", "light", "dimmer", "scenes", "smart home"],
  "versions": [
    {
      "version": "1.0.0",
      "release_notes": "Initial release from NCS 2.5.0.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/bluetooth/mesh/light_dimmer/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_light_dimmer_2.5.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/LBS/peripheral_lbs.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "0e68201e-845d-424b-b3c9-1665b4788ef1",
  "app_name": "Peripheral LBS",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The Peripheral LBS sample demonstrates how to use the LED Button Service (LBS).",
  "tags": ["lbs", "led", "button"],
  "versions": [
    {
      "version": "2.0.0",
      "release_notes": "Initial release",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Blinky for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfblinky"
        },
        {
          "text": "nRF Blinky for iOS",
          "url": "https://apps.apple.com/us/app/nrf-blinky/id1325014347"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.0.0/nrf/samples/bluetooth/peripheral_lbs/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "peripheral_lbs_2.0.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.3.0",
      "release_notes": "Version from NCS 2.3.0.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Blinky for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfblinky"
        },
        {
          "text": "nRF Blinky for iOS",
          "url": "https://apps.apple.com/us/app/nrf-blinky/id1325014347"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.3.0/nrf/samples/bluetooth/peripheral_lbs/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "peripheral_lbs_2.3.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    },
    {
      "version": "2.5.0",
      "release_notes": "Version from NCS 2.5.0.",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Blinky for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfblinky"
        },
        {
          "text": "nRF Blinky for iOS",
          "url": "https://apps.apple.com/us/app/nrf-blinky/id1325014347"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.5.0/nrf/samples/bluetooth/peripheral_lbs/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "peripheral_lbs_2.5.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}

=== NordicSemiconductor/nrfprogrammer-firmware-images/applications/Mesh light/mesh_light.json
{
  "$schema": "https://nordicsemiconductor.github.io/nrfprogrammer-firmware-images/application.schema.json",
  "app_id": "d432882b-87cc-48bd-b858-c49c920d21f1",
  "app_name": "Bluetooth mesh: light",
  "user_id": "00005900-0000-1000-8000-00805F9B34FB",
  "description": "The BluetoothÂ® mesh light sample demonstrates how to set up a mesh server model application, and control LEDs with Bluetooth mesh using the Generic OnOff models.",
  "tags": ["mesh", "light", "led", "smart home"],
  "versions": [
    {
      "version": "2.0.0",
      "release_notes": "Initial release",
      "requires_bonding": false,
      "links": [
        {
          "text": "nRF Mesh for Android",
          "url": "https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfmeshprovisioner"
        },
        {
          "text": "nRF Mesh for iOS",
          "url": "https://apps.apple.com/us/app/nrf-mesh/id1380726771"
        },
        {
          "text": "Documentation",
          "url": "https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.0.0/nrf/samples/bluetooth/mesh/light/README.html"
        }
      ],
      "board": [
        {
          "name": "thingy53_nrf5340",
          "build_config": [
            {
              "name": "release",
              "file": "mesh_light_2.0.0_thingy53_nrf5340.zip"
            }
          ]
        }
      ]
    }
  ]
}
